name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules
        run: rm -rf node_modules

      # - name: Cache modules
      #   uses: actions/cache@v2
      #   with:
      #     # This path is specific to npm
      #     path: ~/.npm
      #     # Use a key for caching dependencies
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm i

      - name: Run format
        run: npm run format

      - name: Commit and push if changes
        run: |
          # Extract author info from the last commit
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "Committing as $AUTHOR_NAME <$AUTHOR_EMAIL>"
          git config --global user.name "$AUTHOR_NAME"
          git config --global user.email "$AUTHOR_EMAIL"
          git add -A
          git diff --staged --quiet || (git commit -m "Format code" && git push)

      - name: Run tests
        run: npm test
