name: Release

on:
  workflow_run:
    workflows: ['Build and Test']
    branches:
      - master
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: svelte-pdf
          versioning-strategy: always-bump-patch
          changelog-path: CHANGELOG.md
